# Generated by Django 4.0.2 on 2022-02-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=20)),
                ('rating', models.IntegerField()),
                ('capacity', models.IntegerField()),
            ],
        ),
    ]
